name: surtaal_app
description: "Surtaal Admin app to manage clases"
publish_to: 'andriod ios web'
version: 1.0.2+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0  # Firebase core package
  cloud_firestore: ^4.8.0  # For Firestore database
  firebase_auth: ^4.20.0  # For authentication
  firebase_storage: ^11.6.5  # For file uploads (photos/videos)
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.2
  lottie: ^2.2.0
  animated_background: ^2.0.0
  flutter_launcher_icons: ^0.14.3 
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/images/surtaal_logo.jpg
    - assets/launch_animation.json
flutter_icons:
  android: true
  image_path: "assets/images/surtaal_logo.jpg"
