// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2hj4i1Wh5cPPfSJKcrXlPOr0yJppYwJM',
    appId: '1:685933490724:web:65223d5014941cb9badeb1',
    messagingSenderId: '685933490724',
    projectId: 'surtaal-2326f',
    authDomain: 'surtaal-2326f.firebaseapp.com',
    storageBucket: 'surtaal-2326f.firebasestorage.app',
    measurementId: 'G-6KMDEC0HFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBomISbAxf8iEL7Jz2i0vQ4f862pobhFqE',
    appId: '1:685933490724:android:1246d78e4d5227d7badeb1',
    messagingSenderId: '685933490724',
    projectId: 'surtaal-2326f',
    storageBucket: 'surtaal-2326f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWV6eEqC9_mEiTjHP6nfJdyMVVagCIGQ',
    appId: '1:685933490724:ios:d23a58212ca93b19badeb1',
    messagingSenderId: '685933490724',
    projectId: 'surtaal-2326f',
    storageBucket: 'surtaal-2326f.firebasestorage.app',
    iosBundleId: 'com.example.surtaalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByWV6eEqC9_mEiTjHP6nfJdyMVVagCIGQ',
    appId: '1:685933490724:ios:d23a58212ca93b19badeb1',
    messagingSenderId: '685933490724',
    projectId: 'surtaal-2326f',
    storageBucket: 'surtaal-2326f.firebasestorage.app',
    iosBundleId: 'com.example.surtaalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2hj4i1Wh5cPPfSJKcrXlPOr0yJppYwJM',
    appId: '1:685933490724:web:c0cf65f6cff2f25ebadeb1',
    messagingSenderId: '685933490724',
    projectId: 'surtaal-2326f',
    authDomain: 'surtaal-2326f.firebaseapp.com',
    storageBucket: 'surtaal-2326f.firebasestorage.app',
    measurementId: 'G-ZFJDM7HR42',
  );
}
